spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://121.40.174.219:3306/dbblog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    host: 121.40.174.219
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
  # elasticsearch配置
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
             enabled: true
  # rabbitMQ配置
  rabbitmq:
    host: 121.40.174.219
    port: 5672
    username: admin
    password: admin



#mybatis-plus
mybatis-plus:
  global-config:
    #刷新Mapper，只在开发环境打开
    refresh: true

# 文件上传
sftp:
  ip: 121.40.174.219
  port: 22
  visit-port: 8090 #文件服务器访问地址
  visit-path: /image/  #图片文件访问路由地址
  username: root
  password: Chrl1992
  downloadSleep: 100 #文件下载失败下次超时重试时间
  downloadRetry: 10 #文件下载失败重试次数
  uploadSleep: 100 #文件上传失败下次超时重试时间
  uploadRettry: 10  #文件上传失败重试次数
  upload-path: /home/file_server/blog/image/

jasypt:
  encryptor:
    password: dbblog-jasypt